import assert from 'node:assert/strict';
import test from 'node:test';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import vm from 'node:vm';
import {deflateSync,inflateRawSync} from 'node:zlib';
import {fileURLToPath} from 'node:url';
import {LABEL,approval,nextRelease,mappingFromDocument,checkApprovedImages,validatePNG,comparablePNG,retryTime,stage,validateReceipt,digest,transaction,verifyLive,checkProductionConflicts,preflight} from './figma-release.mjs';
import {FIGMA_MASTER} from './figma-source.mjs';
import {inventory} from './figma-migrate.mjs';
import {buildPublisher,zipFiles} from './build-figma-publisher.mjs';
import {runPublisher} from '../figma/publisher/plugin.mjs';
import {archiveApproval} from '../figma/publisher/checkpoints.mjs';
const repo=fileURLToPath(new URL('../',import.meta.url));
const A='src/assets/a.png',B='src/assets/b.png',RA='a'.repeat(40),RB='b'.repeat(40);
function crc32(b){let c=0xffffffff;for(const n of b){c^=n;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0);}return(c^0xffffffff)>>>0;}
function chunk(type,b){const t=Buffer.from(type),out=Buffer.alloc(12+b.length);out.writeUInt32BE(b.length);t.copy(out,4);b.copy(out,8);out.writeUInt32BE(crc32(Buffer.concat([t,b])),8+b.length);return out;}
function png(color=0){const sig=Buffer.from([137,80,78,71,13,10,26,10]),h=Buffer.alloc(13);h.writeUInt32BE(2);h.writeUInt32BE(2,4);h[8]=8;h[9]=6;const data=Buffer.alloc(18);for(const i of [1,5,10,14]){data[i]=color;data[i+3]=255;}return Buffer.concat([sig,chunk('IHDR',h),chunk('IDAT',deflateSync(data)),chunk('IEND',Buffer.alloc(0))]);}
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'figma-release-test-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));fs.mkdirSync(path.join(root,'src/assets'),{recursive:true});fs.mkdirSync(path.join(root,'figma'));fs.writeFileSync(path.join(root,A),png());fs.writeFileSync(path.join(root,B),png());fs.writeFileSync(path.join(root,'src/assets/stars.gif'),'GIF89a preserved animation');const manifest={schemaVersion:1,figma:{fileKey:'WJgKfsKcxUpuNkDvxI9gEx',pageId:'27:1966',exportSectionId:'186:410'},policy:{format:'PNG',scale:1,pixelArt:'native-1x'},coverage:{assetFiles:3,figmaExports:2,repoSourceReferences:1},references:[{path:'src/assets/stars.gif',policy:'repo-source-of-truth'}],count:2,items:[A,B].map((p,i)=>({path:p,width:2,height:2,sourceComponentId:`40:${i+1}`,exportNodeId:`50:${i+1}`}))};fs.writeFileSync(path.join(root,'figma/exports.json'),JSON.stringify(manifest,null,2)+'\n');return root;}
function document(version='100'){
 const sources=[A,B].map((p,i)=>({id:`40:${i+1}`,type:'COMPONENT',name:p,absoluteBoundingBox:{width:i?2:4,height:2},fills:[{type:'IMAGE',imageRef:i?RB:RA}]}));
 const frames=[A,B].map((p,i)=>({id:`50:${i+1}`,type:'FRAME',name:p,absoluteBoundingBox:{width:2,height:2},children:[{id:`60:${i+1}`,type:'INSTANCE',componentId:sources[i].id}]}));
 return {version,document:{id:'0:0',type:'DOCUMENT',children:[{id:'27:1966',type:'CANVAS',children:[...sources,{id:'500:1',name:'EXPORTS',type:'SECTION',children:[{id:'500:2',name:'src/assets',type:'FRAME',children:frames}]}]}]}};
}
function version(id='100',paths=[A]){return{id,label:LABEL,created_at:`2026-09-26T00:00:${id==='100'?'01':'02'}Z`,description:JSON.stringify({kind:'cells.garden-ready',fileKey:FIGMA_MASTER.fileKey,target:'dev',assets:paths.map(p=>({path:p,imageRef:p===A?RA:RB}))})};}
function service(v=version(),doc=document(v.id),extra={}){return {versions:[v],api:async u=>u.endsWith('/images')?{images:{[RA]:'https://s3-alpha.figma.com/a',[RB]:'https://s3-alpha.figma.com/b'}}:doc,download:async u=>u.endsWith('/a')?png(100):png(200),...extra};}
const json=p=>JSON.parse(fs.readFileSync(p,'utf8'));

test('only explicit, bounded, correctly scoped approvals are accepted',()=>{const v=version();assert.equal(approval(v,new Set([A,B])).assets.length,1);for(const patch of [{label:'Ready for dev'},{id:'not-a-version'},{description:'invalid'},{description:JSON.stringify({kind:'cells.garden-ready',fileKey:FIGMA_MASTER.fileKey,target:'production',assets:[]})}])assert.throws(()=>approval({...v,...patch},new Set([A,B])));const a=JSON.parse(v.description);a.assets.push({...a.assets[0]});assert.throws(()=>approval({...v,description:JSON.stringify(a)},new Set([A,B])),/duplicate/);a.assets=[{path:'../main.js',imageRef:RA}];assert.throws(()=>approval({...v,description:JSON.stringify(a)},new Set([A,B])));});
test('approval queue is ordered, date-bounded and not replayed',()=>{const a=version(),b=version('101');assert.equal(nextRelease([b,a],null,'2026-09-25').id,'100');assert.equal(nextRelease([b,a],{versionId:'100'},'2026-09-25').id,'101');assert.equal(nextRelease([b,a],{versionId:'101'},'2026-09-25'),null);assert.throws(()=>nextRelease([b],{versionId:'100'},'2026-09-25'),/absent/);assert.equal(nextRelease([a],null,'2026-09-27'),null);assert.equal(nextRelease([{...a,label:'Published'},b],{versionId:'100'},'2026-09-25').id,'101');});
test('live document mapping preserves geometry and validates exact export links',t=>{const root=fixture(t),state=inventory(root),doc=document();const value=mappingFromDocument(state,doc,'100');assert.equal(value.manifest.figma.fileKey,FIGMA_MASTER.fileKey);assert.equal(value.manifest.items[0].sourceWidth,4);assert.equal(value.manifest.items[0].width,2);assert.equal(value.manifest.references.length,1);assert.throws(()=>mappingFromDocument(state,doc,'101'),/exact approved version/);const bad=structuredClone(doc);bad.document.children[0].children[2].children[0].children[0].children[0].componentId='999:1';assert.throws(()=>mappingFromDocument(state,bad,'100'),/local/);});
test('duplicate paths and missing source fills cannot be adopted',t=>{const root=fixture(t),state=inventory(root),doc=document();doc.document.children[0].children[2].children[0].children[1].name=A;assert.throws(()=>mappingFromDocument(state,doc,'100'),/Duplicate/);const bad=document();bad.document.children[0].children[0].fills.push({type:'IMAGE',imageRef:RB});assert.throws(()=>mappingFromDocument(state,bad,'100'),/one original/);});
test('approval fingerprint rejects a checkpoint that missed the latest save',()=>{const a=approval(version(),new Set([A,B]));assert.throws(()=>checkApprovedImages(a,new Map([[A,RB]])),/saved checkpoint/);assert.doesNotThrow(()=>checkApprovedImages(a,new Map([[A,RA]])));});
test('PNG validation rejects corrupt checksums, dimensions and truncation',()=>{assert.deepEqual(validatePNG(png(),2,2),png());assert.throws(()=>validatePNG(png(),3,2),/dimensions/);const b=Buffer.from(png());b[b.length-5]^=1;assert.throws(()=>validatePNG(b,2,2),/checksum/);assert.throws(()=>validatePNG(png().subarray(0,50),2,2));});
test('every current repository PNG passes native integrity checks',()=>{for(const a of inventory(repo).assets)validatePNG(fs.readFileSync(path.join(repo,a.path)),a.width,a.height);});
test('metadata-only image changes preserve original bytes and color profiles matter',async t=>{const root=fixture(t),p=png(),metadata=Buffer.concat([p.subarray(0,33),chunk('tEXt',Buffer.from('Comment\0Local provenance')),p.subarray(33)]);validatePNG(metadata,2,2);assert.deepEqual(comparablePNG(metadata),comparablePNG(p));const gamma=Buffer.alloc(4);gamma.writeUInt32BE(45455);assert.notDeepEqual(comparablePNG(Buffer.concat([p.subarray(0,33),chunk('gAMA',gamma),p.subarray(33)])),comparablePNG(p));fs.writeFileSync(path.join(root,A),metadata);await stage(root,false,service(version(),document(),{download:async()=>p}));assert.deepEqual(fs.readFileSync(path.join(root,A)),metadata);});
test('read-only approval checks do not adopt a mapping or write artwork',async t=>{const root=fixture(t),before=inventory(root).snapshot;const result=await stage(root,true,service());assert.equal(result.status,'checked');assert.equal(result.verified,2);assert.equal(inventory(root).snapshot,before);assert.equal(fs.existsSync(path.join(root,'figma/releases/dev.json')),false);});
test('a late bad download cannot partially publish earlier images',async t=>{const root=fixture(t),before=inventory(root).snapshot;await assert.rejects(stage(root,false,service(version(),document(),{download:async u=>u.endsWith('/a')?png(100):Buffer.from('not a png')})),/PNG/);assert.equal(inventory(root).snapshot,before);});
test('selected artwork only is published; drafts and animation are untouched',async t=>{const root=fixture(t),other=fs.readFileSync(path.join(root,B)),gif=fs.readFileSync(path.join(root,'src/assets/stars.gif'));const result=await stage(root,false,service());assert.equal(result.status,'staged');assert.deepEqual(fs.readFileSync(path.join(root,A)),png(100));assert.deepEqual(fs.readFileSync(path.join(root,B)),other);assert.deepEqual(fs.readFileSync(path.join(root,'src/assets/stars.gif')),gif);const m=json(path.join(root,'figma/exports.json')),receipt=json(path.join(root,'figma/releases/dev.json'));validateReceipt(receipt,m,p=>fs.readFileSync(path.join(root,p)));assert.equal(json(path.join(root,'public/art-release.json')).releaseId,receipt.releaseId);});
test('successive approvals retain cumulative artwork for production',async t=>{const root=fixture(t),a=version();await stage(root,false,service(a));const b=version('101',[B]);await stage(root,false,service(b,document('101'),{versions:[a,b]}));const receipt=json(path.join(root,'figma/releases/dev.json'));assert.deepEqual(receipt.assets.map(a=>a.path),[A,B]);assert.equal(receipt.assets[0].before,digest(png()));assert.equal(receipt.assets[0].after,digest(png(100)));assert.equal(receipt.assets[1].after,digest(png(200)));assert.equal((await stage(root,false,service(b,document('101'),{versions:[a,b]}))).status,'idle');});
test('independent dev edits and repository races stop publication',async t=>{const root=fixture(t),a=version();await stage(root,false,service(a));fs.writeFileSync(path.join(root,A),png(5));await assert.rejects(stage(root,false,service(version('101'),document('101'),{versions:[a,version('101')]})),/outside/);const fresh=fixture(t);let count=0;await assert.rejects(stage(fresh,false,service(version(),document(),{download:async()=>{if(!count++)fs.writeFileSync(path.join(fresh,B),png(9));return png(100);}})),/changed during/);assert.deepEqual(fs.readFileSync(path.join(fresh,A)),png());});
test('publishing rejects unsafe paths and valid-path symlinks before writes',t=>{const root=fixture(t);assert.throws(()=>transaction(root,new Map([['../outside.png',png(8)]])),/Unsafe/);fs.symlinkSync(path.join(root,A),path.join(root,'src/assets/link.png'));assert.throws(()=>transaction(root,new Map([['src/assets/link.png',png(8)]])),/Symlink/);assert.deepEqual(fs.readFileSync(path.join(root,A)),png());});
test('a partial write failure rolls back both completed and partial files',t=>{const root=fixture(t),write=fs.writeFileSync;let failed=false;fs.writeFileSync=function(p,b,...args){if(p===path.join(root,B)&&!failed){failed=true;write.call(fs,p,'partial');throw new Error('simulated disk failure');}return write.call(fs,p,b,...args);};try{assert.throws(()=>transaction(root,new Map([[A,png(7)],[B,png(8)]])),/disk failure/);}finally{fs.writeFileSync=write;}assert.deepEqual(fs.readFileSync(path.join(root,A)),png());assert.deepEqual(fs.readFileSync(path.join(root,B)),png());});
test('production conflicts do not overwrite independent artwork',()=>{const rows=[{path:A,before:digest(png()),after:digest(png(200))}];assert.doesNotThrow(()=>checkProductionConflicts(rows,()=>png()));assert.doesNotThrow(()=>checkProductionConflicts(rows,()=>png(100),new Map([[A,digest(png(100))]])));assert.throws(()=>checkProductionConflicts(rows,()=>png(7)),/independently/);});
test('HTTP 200 from an old deployment is not success',async t=>{const root=fixture(t),marker={releaseId:'c'.repeat(64),versionId:'100',target:'dev'};fs.mkdirSync(path.join(root,'public'));fs.writeFileSync(path.join(root,'public/art-release.json'),JSON.stringify(marker));const previous=globalThis.fetch;t.after(()=>globalThis.fetch=previous);globalThis.fetch=async()=>new Response(JSON.stringify({...marker,versionId:'99'}));await assert.rejects(verifyLive(root,'dev.cells.garden',1),/not verified live/);globalThis.fetch=async()=>new Response(JSON.stringify(marker));assert.equal((await verifyLive(root,'dev.cells.garden',1)).status,'live');await assert.rejects(verifyLive(root,'example.com',1),/Unapproved/);});
test('Retry-After supports seconds and dates without a tight retry loop',()=>{const now=Date.parse('2026-09-25T12:00:00Z');assert.equal(retryTime('3600',now),now+3600000);assert.equal(retryTime('Fri, 25 Sep 2026 14:00:00 GMT',now),now+7200000);assert.equal(retryTime(null,now),now+86400000);});
test('missing credentials produce a setup result, not fabricated readiness',async t=>{const root=fixture(t),old=process.env.FIGMA_TOKEN;delete process.env.FIGMA_TOKEN;t.after(()=>{if(old===undefined)delete process.env.FIGMA_TOKEN;else process.env.FIGMA_TOKEN=old;});assert.equal((await preflight(root)).status,'setup-required');});
test('publisher builds an executable, network-free plugin and valid ZIP payloads',t=>{const root=fixture(t),out=path.join(root,'plugin');const result=buildPublisher(root,out,true);assert.equal(result.pngCount,2);const manifest=json(path.join(out,'manifest.json'));assert.deepEqual(manifest.networkAccess.allowedDomains,['none']);assert.equal(manifest.enablePrivatePluginApi,true);new vm.Script(fs.readFileSync(path.join(out,'code.js'),'utf8'));const files={'one.txt':'hello','two.txt':'world'},zip=zipFiles(files);let at=0;for(const[name,content]of Object.entries(files)){assert.equal(zip.readUInt32LE(at),0x04034b50);const packed=zip.readUInt32LE(at+18),n=zip.readUInt16LE(at+26),start=at+30+n;assert.equal(zip.subarray(at+30,start).toString(),name);assert.equal(inflateRawSync(zip.subarray(start,start+packed)).toString(),content);at=start+packed;}assert.equal(zip.readUInt32LE(at),0x02014b50);});
function fakePlugin(){const messages=[],page={id:'27:1966',type:'PAGE',selection:[]},source={id:'40:1',type:'COMPONENT',parent:page,fills:[{type:'IMAGE',imageHash:RA}]},frame={id:'50:1',type:'FRAME',parent:page};page.selection=[source];let saves=0;const f={fileKey:FIGMA_MASTER.fileKey,editorType:'figma',currentPage:page,ui:{postMessage:m=>messages.push(m)},on(){},getNodeByIdAsync:async id=>id===source.id?source:frame,getImageByHash:()=>({getSizeAsync:async()=>({width:2,height:2})}),saveVersionHistoryAsync:async(title,description)=>{saves++;f.saved={title,description};return{id:'100'};}};const linker=async()=>({rows:[{path:A,width:2,height:2,sourceComponentId:'40:1',exportNodeId:'50:1'}]});return{f,messages,linker,get saves(){return saves;}};}
test('the actual plugin saves explicit approval and only reports queued',async t=>{const x=fakePlugin(),timer=globalThis.setTimeout;globalThis.setTimeout=fn=>{fn();return 1;};t.after(()=>globalThis.setTimeout=timer);let kept=false;await runPublisher(x.f,{assets:[{path:A}],snapshot:'test'},x.linker,async()=>{kept=true;});await x.f.ui.onmessage({type:'ready',all:false});assert.equal(kept,true);assert.equal(x.saves,1);assert.equal(x.f.saved.title,LABEL);assert.deepEqual(JSON.parse(x.f.saved.description).assets,[{path:A,imageRef:RA}]);assert.ok(x.messages.some(m=>m.type==='queued'&&m.text.includes('not yet live')));});
test('the plugin rejects another file and a denied version save',async t=>{const x=fakePlugin();x.f.fileKey='wrong';await runPublisher(x.f,{assets:[]},x.linker);await x.f.ui.onmessage({type:'ready'});assert.equal(x.saves,0);assert.ok(x.messages.some(m=>m.type==='error'));const y=fakePlugin(),timer=globalThis.setTimeout;globalThis.setTimeout=fn=>{fn();return 1;};t.after(()=>globalThis.setTimeout=timer);y.f.saveVersionHistoryAsync=async()=>null;await runPublisher(y.f,{assets:[]},y.linker);await y.f.ui.onmessage({type:'ready'});assert.equal(y.messages.some(m=>m.type==='queued'),false);assert.ok(y.messages.some(m=>m.type==='error'&&m.text.includes('did not confirm')));});
test('approval copies keep image hashes without linked instances or source edits',async t=>{const page={id:'27:1966',type:'PAGE',children:[]},nodes=[];let id=0;const create=type=>{const n={id:`700:${++id}`,type,x:0,y:0,width:100,height:100,children:[],parent:page,resize(w,h){this.width=w;this.height=h;},resizeWithoutConstraints(w,h){this.resize(w,h);},appendChild(c){c.parent.children=c.parent.children.filter(n=>n!==c);this.children.push(c);c.parent=this;}};page.children.push(n);nodes.push(n);return n;};const f={fileKey:FIGMA_MASTER.fileKey,currentPage:page,getNodeByIdAsync:async()=>page,setCurrentPageAsync:async()=>{},getImageByHash:()=>({getSizeAsync:async()=>({width:2,height:2})}),createSection:()=>create('SECTION'),createFrame:()=>create('FRAME'),createRectangle:()=>create('RECTANGLE')};const timer=globalThis.setTimeout;globalThis.setTimeout=fn=>{fn();return 1;};t.after(()=>globalThis.setTimeout=timer);await archiveApproval(f,[{path:A,imageRef:RA}]);assert.equal(nodes.filter(n=>n.type==='INSTANCE').length,0);const rect=nodes.find(n=>n.type==='RECTANGLE');assert.equal(rect.fills[0].imageHash,RA);assert.equal(rect.width,2);assert.equal(rect.parent.locked,true);const count=nodes.length;await assert.rejects(archiveApproval({...f,fileKey:'wrong'},[{path:A,imageRef:RB}]),/master/);assert.equal(nodes.length,count);});
