-- One persistent VAPID pair, generated by the notify function on first use.
-- Private signing material is never exposed to a browser or a build.
create schema if not exists private;
create table if not exists private.push_keys (
    singleton boolean primary key default true check (singleton),
    public_key text not null,
    private_key text not null,
    subject text not null,
    created_at timestamptz not null default now()
);
revoke all on private.push_keys from public, anon, authenticated;
alter table private.push_keys enable row level security;

-- Concurrent cold starts all receive the winning pair, never their own loser.
create or replace function public.service_push_keys(candidate jsonb)
returns jsonb
language plpgsql security definer set search_path = ''
as $$
declare
    keys jsonb;
begin
    if candidate is not null then
        if length(candidate->>'publicKey') <> 87 or length(candidate->>'privateKey') <> 43
           or candidate->>'subject' <> 'https://cells.garden' then
            raise exception 'invalid push keys';
        end if;
        insert into private.push_keys (public_key, private_key, subject)
        values (candidate->>'publicKey', candidate->>'privateKey', candidate->>'subject')
        on conflict (singleton) do nothing;
    end if;
    select jsonb_build_object('publicKey', public_key, 'privateKey', private_key, 'subject', subject)
      into keys from private.push_keys where singleton;
    return keys;
end;
$$;
revoke all on function public.service_push_keys(jsonb) from public, anon, authenticated;
grant execute on function public.service_push_keys(jsonb) to service_role;

-- Devices register through the capped, account-aware RPC only.
revoke insert on public.push_subscriptions from authenticated;
drop policy if exists "push_subscriptions: owner can insert" on public.push_subscriptions;
